### PR TITLE
Add dynamic balances with mock rewards and distribution

### PR DESCRIPTION
**Pull request by shanejearley**
@ccali11 for #295 note the change to contract interfaces. 

Some changed methods: 
- `getUserBalance(userAddress)` to get the stake and rewards for a given user
- `getBalance()` to get the stake and rewards for the manager
- `getStakedPoolIds()` to get staked (active) pool IDs
- `getReadyPoolIds()` to get ready (open) pool IDs
- `getPool(poolId)` to get pool details (deposits, and validator public key and operator IDs if staked)

> Note, rewards will be zero if compound is enabled (`npm run dev:ethereum --compound` or `npm run test:ethereum --compound`) but returned stake will increase as rewards are distributed at large.

### CODE REVIEW

**Comment by shanejearley** [comment]
@hawyar see notes above as this will eventually feed into #256 and happy to discuss before then.

**Comment by shanejearley** [comment]
@ccali11 ok, I'm done making changes to this branch. Once your PR #298 is merged to develop I will merge that into this branch, and then you can work on adapting to the new interfaces in a new branch off of this one (to avoid breaking develop).

**Comment by shanejearley** [comment]
@ccali11 @DemogorGod note the updated dev script flag options in the Serve section [here](https://github.com/consensusnetworks/casimir/tree/feature/balances#serve). We're using the compounding feature by default (Steve you can remove the option switch in the UI for now), and classic mode (no compounding) is behind a flag. The simulation flag might be helpful to auto populate some stakers for development. Also, we're limited to two validators right now (so you'll get an error once you stake enough to activate a third validator). I can remove that limit soon. Rewards are simulated by default, and come in pretty frequently (not set to any realistic cadence at this point), so you can play with displaying updating balances.

In the compounding (default) mode, user rewards will be zero, but their stake will increase as rewards are distributed, by definition.

**Comment by shanejearley** [comment]
Also @DemogorGod just for your awareness, we won't merge this to develop until @ccali11 completes #295 and merges into this branch.

**Comment by ccali11** [comment]
Reviewing this now.

**Comment by shanejearley** [comment]
Done for real, again, btw. Working on additional withdrawal logic and mock exits in the next PR to simulate full withdrawals (`feature/exit`).

**Pull request merged**
