### PR TITLE
Feature/new landing

### PR DESCRIPTION
**Pull request by DemogorGod**
new landing page! 

https://github.com/consensusnetworks/casimir/assets/63758598/9724113f-0b0d-4a79-827c-930615be25e2

### CODE REVIEW

**Comment by ccali11** [comment]
@DemogorGod - **It looks great in the video. Nice work!** Having trouble running this, but more bc of npm related stuff. Was just going to look for responsiveness and grammar issues. I have some feedback to share on the side having to do with color and animations that I think might be helpful; let me know when you have time to hop on discord.

**Review by ccali11 — APPROVED** [review]
See comment in conversation.

**Review by hawyar — DISMISSED** [review]
Changes requested off-thread.

**Comment by DemogorGod** [comment]
New landing 


https://github.com/consensusnetworks/casimir/assets/63758598/7c51f3a2-a2a3-4a63-bfd6-a3a65b34d335

**Pull request merged**
