### PR TITLE
Feature/dynamic chart colors

### PR DESCRIPTION
**Pull request by DemogorGod**
Hey guys! So I did a bit of work on the breakdown chart. I created a method for the app so it fills the chart data with mock data of our own choosing. @ccali11 let me know if you have questions on the changes I made. 

I also adapted the legend labels to show the provider that the account owns and a shortened wallet address (see in the video below) the colors are currently dynamic based on the wallet provider that the user has that account connected with. Since the mock data have multiple wallets and we don't haven't implemented saving user accounts outside of a session and their connected wallets, you'll see that the wallet provider of some of those will be as unknown with a light blue color to them as a default color. otherwise, if we happen to log in using a wallet that matches the mocked data wallets, the colors will change accordingly. 

Enjoy!!!

https://github.com/consensusnetworks/casimir/assets/63758598/c6434b1d-0a14-4627-8845-8e0eb80c690a

### CODE REVIEW

**Comment by DemogorGod** [comment]
@ccali11 if you don't mind please resolve the conflicts, it seems to be in the composable that you are working in. The only one I worked with changed is the `users.ts` I just changed how the txData was imported since I changed the `mock_transaction_data` to a composable style file for easy script setup to fill the JSON object that we are mocking.

**Comment by ccali11** [comment]
> @ccali11 if you don't mind please resolve the conflicts, it seems to be in the composable that you are working in. The only one I worked with changed is the `users.ts` I just changed how the txData was imported since I changed the `mock_transaction_data` to a composable style file for easy script setup to fill the JSON object that we are mocking. 

I got you no problem. I'll be back online tomorrow. 👍

**Comment by ccali11** [comment]
Resolving conflicts now.

**Comment by ccali11** [comment]
https://github.com/consensusnetworks/casimir/assets/15663412/6a585914-3f92-4455-a069-18fa202c6a00

**Review by ccali11 — APPROVED** [review]
Great work, Steve. 👍

**Pull request merged**
