### PR TITLE
Prototype account lookup and send transaction (eth) for two wallet providers

### PR DESCRIPTION
**Pull request by ccali11**
@shanejearley - Per our Slack message an hour or so ago, this PR resolves the following issues:
- #21 
- #23 
- #20 (in researching solutions to these tasks, #20 should be archived as we won't be using WalletConnect to connect to any particular wallets)

It appears there are merge conflicts, so happy to review those with (or before) you. I'll get a new branch going for integrating with the other wallet providers (Ledger, Kepler, Phantom...).

### CODE REVIEW

**Review by shanejearley — CHANGES_REQUESTED** [review]
@ccali11 Good work, caught up offline but noting some of that discussion below.

Edge cases to handle before merging MetaMask and Coinbase Wallet ethereum prototypes:
- [x] `window.ethereum` is undefined when no browser wallets are installed
- [ ] `window.ethereum.providers` and `window.ethereum.providerMap` are undefined when only one browser wallet is installed
- [ ] `window.ethereum.providers` includes the Brave native wallet if available making our `isMetaMask` check unreliable*, so we should switch to `window.ethereum.providerMap` to distinguish the Chrome extensions (please empirically test this with provider calls if you don't mind)

* Brave native wallet does have distinguishable properties from the MetaMask extension (most notably that it's built into the browser), but we'll move this to a separate prototyping issue. I left some debug code on lines `127-137` in @/components/Wallet.vue that logs the distinct keys on each (Brave vs. MetaMask).

**Comment by ccali11** [comment]
@shanejearley - I implemented logic to account for the first two edge cases mentioned in your most recent comment. I'm having a little trouble replicating the issue you described with Brave Wallet overwriting the isMetaMask check. That said, my setup might be slightly off (tested the case where Brave Wallet exists but Brave Browser doesn't have any additional wallet extensions installed - in which case `window.ethereum` is undefined). Worth discussing a little more. 

Could also use your feedback to clean up the logic I introduced to adhere to any code style best practices you can think of.

**Comment by shanejearley** [comment]
> @shanejearley - I implemented logic to account for the first two edge cases mentioned in your most recent comment. I'm having a little trouble replicating the issue you described with Brave Wallet overwriting the isMetaMask check. That said, my setup might be slightly off (tested the case where Brave Wallet exists but Brave Browser doesn't have any additional wallet extensions installed - in which case `window.ethereum` is undefined). Worth discussing a little more.

Great, Chris. Maybe first, can you check your Brave Wallet settings against mine? Nothing really jumps out as crucial here, but that's one place to check.

image

> 
> Could also use your feedback to clean up the logic I introduced to adhere to any code style best practices you can think of.

Yes, sir.

**Comment by shanejearley** [comment]
@ccali11 moving the Brave/MetaMask task to an issue draft, and won't have you take further action unless/until I reproduce on a fresh browser profile. Did add another final task for the composable extraction step we discussed. Looking good!

**Review by shanejearley — CHANGES_REQUESTED** [review]

**Pull request merged**
