### PR TITLE
Feature/connect data to table

### PR DESCRIPTION
**Pull request by DemogorGod**
hey guys! another update, previous update we connected the backend to the front-end line chart component, this pr we used the same data to connect the front-end table on the below components. Enjoy the video!

Note: *** The payload that I got from @ccali11  was missing some items that the front-end had (Status, apy, rewards, and operators) so for now I added it to the mock data and randomized it. 

I think it would be a good conversation for @hawyar @elizyoung0011 to have and adjust either the payload or the front-end to make sense and align. 

Thanks guys, let me know what the changes are for the front-end if there is any and I can update the data or front-end to match in future prs. Thank you! 

https://github.com/consensusnetworks/casimir/assets/63758598/91f30a0b-b8e3-47e4-86c2-89445bb9d354

### CODE REVIEW

**Comment by ccali11** [comment]
@DemogorGod - Looks good. 

@shanejearley - A few questions:

- Is the next step is to hook it up actual wallet history? If so, that would make the tables empty, which is just not ideal for demo purposes (or maybe it is!)
- Would it be better to keep mock data there (maybe at least some of it)? 
- And/or should we write some transactions in the dev script to populate the table so it's not empty for demo purposes? 
- I think some of the fields need to be updated/added/removed from the table

Let me know what you think.

**Comment by DemogorGod** [comment]
@ccali11 want to add a review?

**Comment by shanejearley** [comment]
@ccali11 You can keep mock FE data for now. @hawyar is working on a PR that will support crawling data for our local hardhat network (it will be easier to explain online). I think we'll be covered for demo data.

Going to suggest some new (display) table columns here based on previous convos with @elizyoung0011. 

Wallets:

`Wallet provider | Account | Wallet balance | Stake balance | Stake rewards (all-time)`

Transactions and Staking actions might need to be two distinct tabs, but they both can use the columns:

`Date | Account | Type | Amount | Description | Status | Hash`

- Hash might be fine to put on the right side end as secondary info (but keep date on the left for easy sorting), and both transactions and staking actions will have a TX hash
- Type for a transaction is either `Sent` or `Received`, and type for a staking action is the event type (i.e., Stake deposit, Withdrawal request, Withdrawal fulfillment) 
- Amount for a transaction is the amount sent or received, and amount for a staking action is derived from the event value (i.e. StakeDeposit.amount is the stake amount)
- Description would then contain details of the transaction or staking action

**Review by shanejearley — APPROVED** [review]
Nice work, we'll follow up on the table comments in the next PR.

**Pull request merged**
