### PR TITLE
Feature/multi account management

### PR DESCRIPTION
**Pull request by ccali11**
@shanejearley - Re-added the multi-account management logic that we had prior to the front-end overhaul/refactors. Much cleaner now and I'm passing @DemogorGod `UserAuthState`s in `default-layout.vue` to help manage and communicate with the user when they try to add an account by selecting an address from the popup modal.

@DemogorGod - Leaving the initialization of WalletConnect in `useAuth` for now; I will be testing and refining WalletConnect implementation in another PR soon so will leave it there for now as it functions nicely for the basic use case of logging in / adding account and performing smart contract actions.

### CODE REVIEW

**Comment by ccali11** [comment]
Love it. Lmk if you need me to clarify anything.

**Comment by ccali11** [comment]
@shanejearley - @DemogorGod and I are now handling most if not all user auth flow states with UI/UX enhancements. There will still be some improvements to make, but I think this is good to merge in once approved. See video below to show user creating a new Casimir account with MetaMask Account 1, adding address from MetaMask Account 2, signing out, and then trying to add a new Casimir account with MetaMask Account 2; we prompt them accordingly.

https://github.com/consensusnetworks/casimir/assets/15663412/8e65e6a0-8b21-47b0-94e3-ede5d756eae5

**Review by DemogorGod — CHANGES_REQUESTED** [review]
image

Need to remove the randomizer in ConnectWalletsFlow

**Comment by ccali11** [comment]
@shanejearley @DemogorGod - I think this is ready to merge. I fixed the issue of Trust Wallet interfering with MetaMask and CoinbaseWallet (the other browser extension wallets we currently support), but @DemogorGod - I left the task for building out the method `detectingInstalledProviders` for another PR. I do believe it is a cool feature, so I did start building towards it (see new `wallets` composable), but I believe it may require a more complex build-out that is probably out of scope for this PR considering we should push the critical UI updates to the user auth flow to production.

**Review by DemogorGod — APPROVED** [review]
sounds good @ccali11 good work!

**Pull request merged**
