### PR TITLE
Add account, nonce, and user schemas, and mock Postgres

### PR DESCRIPTION
**Pull request by shanejearley**
See the [@casimir/data README](https://github.com/consensusnetworks/casimir/blob/feature/pg/common/data/README.md) for background (and ignore the Jupyter notebooks).

For convenient iteration, running `npm run dev` (scripts/local/dev.ts) now hits `npm run watch:postgres --workspace @casimir/data` when local mock is enabled (default). The database reloads any changes from the @casimir/data [schema files](https://github.com/consensusnetworks/casimir/blob/feature/pg/common/data/src/schemas). 

See a usage example in the @casimir/users service `/user` route (getUser from useDB).

Remaining task(s):
- [x] Show stdout from spawn process in terminal (to notify when database is reloaded/ready)

_Infrastructure, migrations, and environment variables are coming in a PR next week._

### CODE REVIEW

**Comment by shanejearley** [comment]
@ccali11 also added a seed script to `users` API. So to get up and running.

1. Run development server with mock `@casimir/user` API and mock `@casimir/data` database with default `accounts`, `nonces`, and `users` tables. 
    ```zsh
    npm run dev # --clean=false to keep data/database from previous run
    ```
2. Seed the database with mock store of users from `@casimir/users/src/mock/user.store.json`. (Right now just one user – this primary account is also added to accounts.)
    ```zsh
    npm run seed --workspace @casimir/users # --resource=account to seed with something like `@casimir/users/src/mock/account.store.json` instead. Just add a mock store file and also a corresponding path to the /seed route.
    ```
3. Editing the schema files in `@casimir/data/src/schemas` will reload the database. This takes a minute, but in the meantime, there are manual changes sometimes need to be made (like changing the mock store data or `@casimir/types`). 

_With some optimization as we go, this can become much faster and convenient with better database bootstrapping and type generation (@hawyar is looking into schema-to-type generation)._

**Comment by hawyar** [comment]
This sets great foundation for schema changes and using the JSON schema allows us to safely generate TS types. I have a working [example](https://github.com/hawyar/typegen) that works with all our current schemas.

To generate correct types for properties of type `array` and `object` we should add the `items` properties. For example,  the `snapshot` could be represented as `snapshot: Array<Snapshot>` instead of just `Array<any>`. Same goes for `transactions: Array<Transaction>`

Example:
```json
"snapshot": {
  "type": "array",
  "description": "The account snapshots",
  "items": {
    "type": "object",
    "properties": {
      "date": {
        "type": "string",
        "description": "The date of the snapshot in ISO 8601 format"
      },
      "balance": {
        "type": "number",
        "description": "The balance of the snapshot"
      },
      "anotherprop": {
        "type": "string"
      },
    },
    "required": [
      "date",
      "balance"
    ]
  }
}
```
and the type output would look something similar to:
```ts
interface Snapshot {
  date: string;
  balance: number;
}

interface Account {
  snapshots: Array<Snapshot>;
  transactions: string[];
  // the rest
}
```

**Comment by shanejearley** [comment]
@hawyar Great! Thank you and nice work. Do you want to commit a change to add the array items field where it's currently needed?

**Comment by hawyar** [comment]
Sounds good. After this is merged I will add typegen and update the rest of the schema as needed.

**Comment by shanejearley** [comment]
Adding one more commit to speed up live changes.

**Review by ccali11 — APPROVED** [review]
@shanejearley @hawyar Looks great, guys. Will dive into this with my tasks this week and note any opportunities for changes/improvements.

**Comment by shanejearley** [comment]
Nevermind, ready to review workflow and merge whenever. Schema reloads will be slow but will become much faster once we add proper migrations for schemas (which will be required when we add the deployment infra anyways).

**Comment by ccali11** [comment]
@shanejearley - did you want a sync review before merging? up to you.

**Pull request merged**
