### PR TITLE
Add polyfill for node stream to @casimir/web

### PR DESCRIPTION
**Pull request by shanejearley**

### CODE REVIEW

**Comment by shanejearley** [comment]
Everything should work as expected with 'bitcoin' and 'ethereum' apps on Ledger NanoS via WebUSB. I was unable to resolve the issue with the 'bitcoin' app and the Speculos NanoS emulator (but 'ethereum' app works) so I'll make an issue for that.

**Comment by shanejearley** [comment]
Try it out and confirm things are working after an npm run clean. Then merge to `feature/bitcoin` whenever you've confirmed.

**Review by ccali11 — APPROVED** [review]
@shanejearley - This is all working like a charm. I switched up the default bitcoin address to be Native Segwit, which required a change to the `path` and `format` option that are passed into the ledger `Btc` app / class.

**Comment by shanejearley** [comment]
Good to merge?

**Comment by ccali11** [comment]
Yes! Merging!

**Comment by ccali11** [comment]
I'll run it quickly and then submit the PR. :)

**Pull request merged**
