### PR TITLE
Add operator page and mock data for it as well

### PR DESCRIPTION
**Pull request by DemogorGod**
Hey guys, just created a new operator page as requested. i used https://excalidraw.com/#room=11291b0aa3112316b710,gsI_wIEmxAd5oIABEStm3Q as my guide of building it, it was very helpful! here is a short clip of what it looks like as of right now. Thanks!! 

I'll fix and responsiveness issue with the new responsiveness pr that I will put up soon, Thanks for being patient with me! 

@ccali11 there are comments in this component for you to pull and connect with your composables as you see fit, any wording change or other changes that seem reasonable that you think are needed. 

https://github.com/consensusnetworks/casimir/assets/63758598/bcec817e-c6a1-4950-b866-9798621fef15

### CODE REVIEW

**Comment by hawyar** [comment]
Increase the height of the modal and decrease its width to be the size of its content + some padding. That will also get rid of the scroll on the modal. Great work

**Comment by ccali11** [comment]
Really great work, Steve. I will merge this branch into mine and hook up the composables to the operator data.

**Review by ccali11 — APPROVED** [review]
Really great work, Steve. I will merge this branch into mine and hook up the composables to the operator data. May need to just fix up the build errors.

**Review by hawyar — APPROVED** [review]

**Comment by ccali11** [comment]
@DemogorGod - You may want to extract the code that has to do with `Export` to a composable or something; especially because I think we have that functionality available in other components.

**Comment by ccali11** [comment]
And would you consider making the modal a separate component or nah?

**Pull request merged**
