### PR TITLE
Deploy contracts and configure variables

### PR DESCRIPTION
**Pull request by shanejearley**
I can merge this after the other existing PRs and then we can test. We should be able to run the app against the Goerli network (with all contract addresses available as variables) by setting NETWORK=testnet in .env and `npm run dev`. But it will be good to work through together that on the operator page step by step to smooth things out.

### CODE REVIEW

**Comment by ccali11** [comment]
@shanejearley - am I waiting to work sync with you on this one?

**Comment by ccali11** [comment]
> merge this after the other existing PRs and then we can test. We should be able to run the ap

@shanejearley ?

**Comment by shanejearley** [comment]
Let me know when's a good time and I'll resolve the conflicts, merge, and send a note for your quality testing of the latest operator registration from develop.

**Comment by shanejearley** [comment]
Tweaking a few things for futureproofing before being done anyways. No rush. If you want to finish any composable refactor first.

**Review by ccali11 — APPROVED** [review]
Great job, @shanejearley! 👍

**Pull request merged**
