### PR TITLE
Add Phantom wallet integration with prototype transaction

### PR DESCRIPTION
**Pull request by ccali11**
@shanejearley - This is a PR covering #53; prototyping the Phantom Wallet integration. Please let me know if you have any questions; I will move onto Keplr Wallet #52 next.

### CODE REVIEW

**Comment by shanejearley** [comment]
Just holding this hostage until the build issue is fixed. The code looks ready to go for when that happens!

I will prioritize the ledger dev setup so it may take a day or so to get this merged. I will keep you posted.

**Comment by ccali11** [comment]
@shanejearley - is there any action for me to take? I see you made a commit with message `Fix borsh package build`, but there also appears to be conflicts in the package-lock.json file. If you know why that is, teach me.

**Comment by shanejearley** [comment]
Chris, I will let you know when I come back to this. No action to take at the moment.

**Comment by shanejearley** [comment]
Redone with latest wallet composables in #143

**Pull request closed without merging**
