### PR TITLE
Feature/functional components

### PR DESCRIPTION
**Pull request by DemogorGod**
Worked on making most of the components functional. 

- switched icon library to feather-vue icons instead of plain feather-icons (it was buggy on vue)
- connect wallet component is functional, in the clip it doesn't show the connected wallet addresses because I didn't have metamask connected. will need to show that somehow in the later versions (probably talk to @ccali11 about it) 
- updated the line chart to work with the button group, the data is currently random but once I get the data from @elizyoung0011 and @hawyar  it'll work. 
- Staking component is fully functional, it's only waiting to be connected with the real methods of staking and perhaps add an alert once it is successful. balance, amount to stake will all be dependent on how i get the wallet that is selected and the amount that is under that wallet. Will need the terms of services agreement written out from @natemiller1 or @elizyoung0011 
- Staking average component is also functional and dynamic just waiting on data plugin
- The announcement component is also functional and dynamic with the entire page.  will need the updated data and format plugin at some point 
- The bottom table is close to completion, the export button has a function where it checks if you have a mac or a windows and from there will export a file according to the type it finds and the table view that is selected. I implemented a small search method for now since we have a small data (later versions will be based on a query, waiting on @hawyar  and @elizyoung0011  for that), I also implemented an ascending and descending method that works (Might have to tweak it depending on what the schema will look like once i get it. 

enjoy the clips :)

https://github.com/consensusnetworks/casimir/assets/63758598/b0247033-1aae-4558-be6f-2cabbff6eeb4

https://github.com/consensusnetworks/casimir/assets/63758598/b74e32e5-43ab-4c9f-a3cd-435d0ddafdc5

### CODE REVIEW

**Review by hawyar — APPROVED** [review]
Great work

**Comment by shanejearley** [comment]
Awesome Steve! You mentioned getting with Chris – check out #350. Relates to connecting bullet number 2 and 4, whenever @ccali11 is ready.

**Comment by natemiller1** [comment]
A few design comments:
Let's hide the IoPay wallet for now
I think most people will natively choose an amount of ETH to stake vice USD. For example, I will likely try and stake 0.2 ETH vice $400. Using USD would be complicated because you'll have to pull a conversion value from USD to ETH as well (may be an option for the future though).
@hawyar Design consideration for the black bar header? Is that just a placeholder for now?

**Comment by hawyar** [comment]
> @hawyar Design consideration for the black bar header? Is that just a placeholder for now?

The dark background on the top is mostly for form not function. I don't have any functional use in mind for that space otherwise please advise.

**Pull request merged**
