### PR TITLE
Update/v1

### PR DESCRIPTION
**Pull request by ccali11**
1. Renamed `landing` to `www`
2. Added `app` directory within `apps` for @DemogorGod to begin implementing his designs from scratch (created the directory using `vite create`, selected `vue`, and `Typescript` and then ported over a few configs from "mvp" `web` app. 
3. Kept `web` for reference, but `npm run dev` from root points to new `app` workspace

### CODE REVIEW

**Comment by DemogorGod** [comment]
Naming-wise, www and app don't make sense to me. Not sure what the standard is. What is the purpose of naming them www and app? Will the operator, institutional, and pro versions not be considered as apps? I think we should just call them as casimir-landing, casimir-app, casimir-pro, casimir-institutional, and casimir-operators

@shanejearley @ccali11 thoughts?

**Comment by shanejearley** [comment]
@DemogorGod This is just my biased version of that standard: just putting the apps into a directory with same name as the subdomain. So www is found at www.casimir.co (or the casimir.co short name) as app corresponds with app.casimir.co and so on. As we go, operators, pro, institution, all follow that same standard.

**Comment by shanejearley** [comment]
@DemogorGod @ccali11 also don't mind keeping landing and web for the package/directory names in those cases since both those names are special cases for the main website and web app respectively. Either works if you want to make a final call @ccali11.

I'll check back on the configuration once we've settled it and then we can merge.

**Comment by ccali11** [comment]
@shanejearley -I think we'll keep as is. Let me know if you need any assistance checking configuration. 

Also looks like checks are failing (I believe it has to do with the way `tsx` is installed with node v20 (I thought we were using 18)). Let me know if that's an easy one for you or if you want me to tackle that.

**Comment by ccali11** [comment]
You going to approve? Or have more to review?

**Comment by shanejearley** [comment]
@ccali11 @DemogorGod @hawyar We'll need to update our local node versions as well (LTS switched from 18 to 20).

```zsh
nvm install --lts
```

Should do the trick. Also updated prerequisites in README and check. So you'll get an error on install if the version is mismatched.

**Comment by shanejearley** [comment]
@ccali11 needing to fix one more thing before merge.

**Review by shanejearley — APPROVED** [review]

**Review by shanejearley — CHANGES_REQUESTED** [review]
Hang on.

**Review by shanejearley — APPROVED** [review]

**Pull request merged**
