### PR TITLE
Feature/more fe integration

### PR DESCRIPTION
**Pull request by DemogorGod**
me and your boi @ccali11 got some more front-end connection done! 

Enjoy!

https://github.com/consensusnetworks/casimir/assets/63758598/24ab4311-365a-4350-abb0-2ff0250e5ad2

### CODE REVIEW

**Comment by shanejearley** [comment]
@DemogorGod @ccali11 are we just closing this one?

**Comment by ccali11** [comment]
> @DemogorGod @ccali11 are we just closing this one?

Not sure. What makes you say to just close?

**Comment by shanejearley** [comment]
Sounds good. I thought I heard Steve mention that most of it was in your latest PRs.

**Review by ccali11 — APPROVED** [review]
Good stuff. Approved.

**Pull request merged**
