### PR TITLE
Feature/screen response

### PR DESCRIPTION
**Pull request by DemogorGod**
Just trying to make the app more responsive, nothing more nothing less. some of the views are subject to change based on how Howie decides those views should look like on different screens but for now, I have it so it changes and nothing gets lost outside of the view or looks off. 

@hawyar let me know how you want the table to look on the smaller screens so i can implement that in a different pr in the future. for now i made it into a list as you can see in the video. 

https://github.com/consensusnetworks/casimir/assets/63758598/674dbbfa-99fa-47d8-8b41-0a6c7b060d44

### CODE REVIEW

**Review by ccali11 — APPROVED** [review]
Sweet. Moving in the right direction for sure. I like how when going from medium size to large the components animate into position. Would be curious if you could hide them in a similar fashion as well.

Something you might consider improving here or in the future, when going from large to medium size screen there is a lot of space between components below APY component:

image

**Review by hawyar — CHANGES_REQUESTED** [review]
There is some noticeable lag when you resize, is it because of the recording or a certain animation is causing the delay?

For now we care mostly for 3 breakpoints widths (1280px for desktop, 834px for tablet, and ~400px for mobile). These are rough estimates, anything around that should be fine. For very wide large screens (>1280px) there should be a `max-width` to avoid the elemetns stretch to the edge.

For smaller screen (tablet and below) the components should simply stack on top of each other and stretch to fill the width. Other adjustments include smaller font sizes, margin, and padding inside and outside the component. For elements that can't be adjusted to stack you can re-position them in context. For example the "connect wallet" button could appear below the nav and the links would appear as a hamburger menu.

mobile

Regarding the table and other components that require horizontal space like the chart they should maintain their width and only appear inside the component. The user should be able to scroll across the x-axis to see the rest of the chart (or table). Setting the chart (or table) to `overflow: hidden` and its parent container to `overflow: auto` allows that.

In the screenshot below I have intentionally left out the part that would be scrollable across the x-axis (normally it would be hidden). Feel free to reorganize the elements on smaller screen as you see fit. For example, notice the component on the right has the search bar and filter menu below the tab to make the inputs easier to click on smaller devices. 

xaxis

**Comment by DemogorGod** [comment]
@hawyar so the lag is due to inspecting the page's width, once i stop inspecting the page the lag goes away. That lag is caused on any webpage if you are constantly inspecting it's width. 

I changed the breakpoints to 1000px, 800px, and some of them at 600px it just seemed smother that way. anything below that stays the same and the page does not get below 360px (which is standard for the smallest screen size) 

thanks for the input on the width being maxed out to fill the screen. 

Enjoy the video!


Uploading Screen Recording 2023-06-05 at 10.15.03 AM.mov…

**Comment by ccali11** [comment]
> @hawyar so the lag is due to inspecting the page's width, once i stop inspecting the page the lag goes away. That lag is caused on any webpage if you are constantly inspecting it's width.
> 
> I changed the breakpoints to 1000px, 800px, and some of them at 600px it just seemed smother that way. anything below that stays the same and the page does not get below 360px (which is standard for the smallest screen size)
> 
> thanks for the input on the width being maxed out to fill the screen.
> 
> Enjoy the video!
> 
>  Screen.Recording.2023-06-05.at.10.15.03.AM.mov

Sexy.

**Review by hawyar — APPROVED** [review]

**Pull request merged**
