### PR TITLE
Feature/iotex actions

### PR DESCRIPTION
**Pull request by hawyar**
Following our conversations on the schema, updated the schema to meet our current needs.

Event schema:
- chain
- network
- provider
- type
- height
- date
- address
- to_address
- candidate
- candidate_list
- amount
- duration
- auto_stake

I left payload out for now. Let's keep this PR open since `retrieveLastBlock` still needs work.

### CODE REVIEW

**Comment by shanejearley** [comment]
@hawyar can you update [schemaToGlueColumns](https://github.com/consensusnetworks/casimir/blob/feature/iotex-actions/common/data/src/index.ts#L13) to convert the event table `date` property from the JSON schema `string` to the Glue `DATE` type as it is used [here](https://github.com/consensusnetworks/casimir/blob/master/infrastructure/cdk/lib/etl/etl-stack.ts#L7) to deploy the table? Can you also update the agg table `date` property in the same move?

**Review by shanejearley — CHANGES_REQUESTED** [review]
@hawyar can you update [schemaToGlueColumns](https://github.com/consensusnetworks/casimir/blob/feature/iotex-actions/common/data/src/index.ts#L13) to convert the event table `date` property from the JSON schema `string` to the Glue `DATE` type as it is used [here](https://github.com/consensusnetworks/casimir/blob/master/infrastructure/cdk/lib/etl/etl-stack.ts#L7) to deploy the table? Can you also update the agg table `date` property in the same move?

**Comment by hawyar** [comment]
Changed `date` to `created_at` and `first_created_at` from the Agg schema remains the same. [schemaToGlueColumns](https://github.com/consensusnetworks/casimir/blob/feature/iotex-actions/common/data/src/index.ts#L13) checks the `_at` to assign the Date Glue type.

**Comment by shanejearley** [comment]
Super cool. That should fix work perfectly.

Making a quick commit to fix the existing conflict so we can develop and run a simple CI test for the tables on the CDK side.

**Review by shanejearley — APPROVED** [review]

**Review by shanejearley — CHANGES_REQUESTED** [review]
@hawyar can play with a couple of things:
-  In [schemaToGlueColumns](https://github.com/consensusnetworks/casimir/blob/feature/iotex-actions/common/data/src/index.ts#L13), convert `candidate_list` from `array` to `glue.Schema.array(glue.schema.STRING)`
- Or, change `candidate_list` from `array` to `string` with commas
- Finally, get CDK [tests](infrastructure/cdk/test/) passing (`npm run test --workspace @casimir/cdk`) – either of the changes above should do the trick! But you can add more testing if you see fit

**Comment by shanejearley** [comment]
@hawyar excellent, now just waiting on `retrieveLastBlock` and then we'll take a final pass.

**Comment by hawyar** [comment]
`retrieveLastBlock` is complete and works. I didn't add tests because the schema isn't updated yet

**Comment by shanejearley** [comment]
Looks good to merge!

**Pull request merged**
