### PR TITLE
Add SSV pool details and change to ID

### PR DESCRIPTION
**Pull request by shanejearley**
See the bottom of `apps/web/src/composables/wallet.ts` changes for some updated composable handling of the pool details available. Note `poolAddress` is now `poolId` (just an integer, we'll display #1, #2, etc.) and a `Balance` is made up of `stake` and `rewards`.

Regarding the script issues, see `scripts/ethereum/dev.ts` line 38. Needed to pass the localhost network to the deploy script after starting up the hardhat network (which was why it was confusing, but I knew that and still removed it at some point). Your hunch at the beginning (is the contract deployed) was actually spot on. It was being deployed on a separate network!

Please ignore the mid-stage contract changes other than the ones related to the methods currently used in `apps/web/src/composables/wallet.ts` (`getUserPoolIds`, `getPoolUserBalance`, `getPoolBalance`, etc.).

### CODE REVIEW

**Comment by ccali11** [comment]
@shanejearley - Pulled this down and wasn't able to run it successfully. I am able to confirm staking, but the `wallet.ts` method `getUserPools` is throwing a similar if not the same error. Will investigate further, but if you find yourself online today, ping me. 👍

**Comment by shanejearley** [comment]
Sorry, I actually have the fixes in the next PR.

**Comment by shanejearley** [comment]
Ok pushed up the fixes. Note, this is another midway PR (with some unfinished portions) from me, apologies. At the least, the script should be all set. 

Reminder to reset the Metamask account every time you restart the network after transacting.

**Review by ccali11 — APPROVED** [review]
Pulled down and ran. Looks great.

**Pull request merged**
