### PR TITLE
Add rewards oracle integration

### PR DESCRIPTION
**Pull request by shanejearley**

### CODE REVIEW

**Comment by shanejearley** [comment]
@ccali11 will fix the merge conflicts, but **do you mind taking note of the tiny changes in wallet.ts**? Those were resulting from some minor upstream contract changes. Then, if you wouldn't mind giving a fast approval, I need to merge this in order to pivot to some other (infrastructure) work in a new PR (some of which will benefit your upcoming work). I don't need a thorough review of the rewards oracle changes, since I'm going to change to something slightly different in the near term anyway.

**Comment by shanejearley** [comment]
Ok fixed conflicts.

**Review by ccali11 — APPROVED** [review]
@shanejearley - `wallet.ts` looks great. Thanks for sharing. 👍

**Comment by shanejearley** [comment]
Made some other small name changes. Merging now.

**Pull request merged**
