### PR TITLE
Feature/staking page

### PR DESCRIPTION
**Pull request by DemogorGod**
A lot of work since the last update, the video speaks for itself 
the only thing not shown in the video is that I removed 2.0

https://user-images.githubusercontent.com/63758598/205810421-ec60a59f-713b-40e1-9890-0c02aeafcdfe.mov

### CODE REVIEW

**Review by shanejearley — CHANGES_REQUESTED** [review]
@DemogorGod Good redesign based on a recent decision to remove the chart. Can we make the top section larger and make some of these numbers easier to pick out (otherwise everything is the same size) by making them bigger and then making smaller/shorter their labels: "Stake" (total amount can be omitted since at the top level it is implied), "Rewards" (same, can omit total amount), and "APR". Maybe don't limit the creative space to chips since these are the primary information/values. The pool list and details contain secondary information/values. I also don't know if we need Fees at the top, which is shown during the stake transaction flow.

Coming along great, good progress, let's keep it up!

**Comment by DemogorGod** [comment]
> @DemogorGod Good redesign based on a recent decision to remove the chart. Can we make the top section larger and make some of these numbers easier to pick out (otherwise everything is the same size) by making them bigger and then making smaller/shorter their labels: "Stake" (total amount can be omitted since at the top level it is implied), "Rewards" (same, can omit total amount), and "APR". Maybe don't limit the creative space to chips since these are the primary information/values. The pool list and details contain secondary information/values. I also don't know if we need Fees at the top, which is shown during the stake transaction flow.
> 
> Coming along great, good progress, let's keep it up!

The video doesn't do the app justice, everything is super clear and easy to read on all screen sizes
I think the top section is a good size for all screen sizes and based on our text hierarchy it fits the way it is 
making them larger will affect the way the app looks especially as pills (I have plans for the pills to be dynamic and animated)

I will emit fees, and shorten the text as well to see how it looks.

**Comment by DemogorGod** [comment]
new pill look

Screenshot 2022-12-06 at 2 55 00 PM

**Comment by hawyar** [comment]
It is best to keep the routes lower case and without `ing`.
`/Staking` -> `/stake`
`/Staking/ETH` -> `/stake/eth`

I recommend removing the transition to get the layout and content right first. These animations causes the layout to shift which could produce janky animations. 

Usually it is better to use something close to `#181818` rather than all black `#000000` for the sidebar

**Pull request merged**
