### PR TITLE
Clean landing app

### PR DESCRIPTION
**Pull request by DemogorGod**
Hey Y'all,

Just made cleaned up the landing application with the following:

- Added router flow to match future routes
- Started to import Audāx into the application (Typography, coloring, layout, and components)
- Created a Home page that links up with our social media
- Made sure the application is responsive throughout different sizes and layouts

Uploaded a video of its responsiveness and functionality
https://user-images.githubusercontent.com/63758598/196898834-9a2fa4ed-75ea-46e5-bcd1-a8d303461958.mov

currently, there are no other pages, and the image on the right is not dynamic, will include right-side animation and dynamic movement once the design is complete.

### CODE REVIEW

**Review by shanejearley — APPROVED** [review]
Looks good so far Steve. Note I added a commit to resolve the merge conflicts.

**Comment by shanejearley** [comment]
Made one more commit to remove imports and variables that depended on missing components and composables.

**Comment by DemogorGod** [comment]
What is the reason that router needs to be ts? @shanejearley 

Since the traditional way is to use js files, and we aren't passing in variables that require type verification I do not think they need to be ts files, especially when they throw ts errors.

**Comment by shanejearley** [comment]
TS for the Vue app please. Caught two errors before build by adding it. You should be able to pull down and see things error-free in the editor and in dev server -- if anything shows up let me know!

**Pull request merged**
